#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = `wx-config --cflags` -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `wx-config --libs`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Signin

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/Signin

OBJ_DEBUG = $(OBJDIR_DEBUG)/config/Config.o $(OBJDIR_DEBUG)/certcard/CertCard.o $(OBJDIR_DEBUG)/camera/CameraView.o $(OBJDIR_DEBUG)/ProgressThread.o $(OBJDIR_DEBUG)/SigninMain.o $(OBJDIR_DEBUG)/SigninFrame.o $(OBJDIR_DEBUG)/SigninApp.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/config/Config.o $(OBJDIR_RELEASE)/certcard/CertCard.o $(OBJDIR_RELEASE)/camera/CameraView.o $(OBJDIR_RELEASE)/ProgressThread.o $(OBJDIR_RELEASE)/SigninMain.o $(OBJDIR_RELEASE)/SigninFrame.o $(OBJDIR_RELEASE)/SigninApp.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/config || mkdir -p $(OBJDIR_DEBUG)/config
	test -d $(OBJDIR_DEBUG)/certcard || mkdir -p $(OBJDIR_DEBUG)/certcard
	test -d $(OBJDIR_DEBUG)/camera || mkdir -p $(OBJDIR_DEBUG)/camera
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/config/Config.o: config/Config.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c config/Config.cpp -o $(OBJDIR_DEBUG)/config/Config.o

$(OBJDIR_DEBUG)/certcard/CertCard.o: certcard/CertCard.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c certcard/CertCard.cpp -o $(OBJDIR_DEBUG)/certcard/CertCard.o

$(OBJDIR_DEBUG)/camera/CameraView.o: camera/CameraView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c camera/CameraView.cpp -o $(OBJDIR_DEBUG)/camera/CameraView.o

$(OBJDIR_DEBUG)/ProgressThread.o: ProgressThread.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ProgressThread.cpp -o $(OBJDIR_DEBUG)/ProgressThread.o

$(OBJDIR_DEBUG)/SigninMain.o: SigninMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SigninMain.cpp -o $(OBJDIR_DEBUG)/SigninMain.o

$(OBJDIR_DEBUG)/SigninFrame.o: SigninFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SigninFrame.cpp -o $(OBJDIR_DEBUG)/SigninFrame.o

$(OBJDIR_DEBUG)/SigninApp.o: SigninApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SigninApp.cpp -o $(OBJDIR_DEBUG)/SigninApp.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/config
	rm -rf $(OBJDIR_DEBUG)/certcard
	rm -rf $(OBJDIR_DEBUG)/camera
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/config || mkdir -p $(OBJDIR_RELEASE)/config
	test -d $(OBJDIR_RELEASE)/certcard || mkdir -p $(OBJDIR_RELEASE)/certcard
	test -d $(OBJDIR_RELEASE)/camera || mkdir -p $(OBJDIR_RELEASE)/camera
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/config/Config.o: config/Config.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c config/Config.cpp -o $(OBJDIR_RELEASE)/config/Config.o

$(OBJDIR_RELEASE)/certcard/CertCard.o: certcard/CertCard.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c certcard/CertCard.cpp -o $(OBJDIR_RELEASE)/certcard/CertCard.o

$(OBJDIR_RELEASE)/camera/CameraView.o: camera/CameraView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c camera/CameraView.cpp -o $(OBJDIR_RELEASE)/camera/CameraView.o

$(OBJDIR_RELEASE)/ProgressThread.o: ProgressThread.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ProgressThread.cpp -o $(OBJDIR_RELEASE)/ProgressThread.o

$(OBJDIR_RELEASE)/SigninMain.o: SigninMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SigninMain.cpp -o $(OBJDIR_RELEASE)/SigninMain.o

$(OBJDIR_RELEASE)/SigninFrame.o: SigninFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SigninFrame.cpp -o $(OBJDIR_RELEASE)/SigninFrame.o

$(OBJDIR_RELEASE)/SigninApp.o: SigninApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SigninApp.cpp -o $(OBJDIR_RELEASE)/SigninApp.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/config
	rm -rf $(OBJDIR_RELEASE)/certcard
	rm -rf $(OBJDIR_RELEASE)/camera
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

