#ifndef __SigninMain__
#define __SigninMain__

/**
@file
Subclass of SigninFrame, which is generated by wxFormBuilder.
*/

#include "SigninFrame.h"
//// end generated include
#include <wx/progdlg.h>
#include "./camera/CameraView.h"

/** Implementing SigninFrame */
class SigninMain : public SigninFrame
{
	protected:
		CameraView * m_CameraView;

		// Handlers for SigninFrame events.
		void OnClose( wxCloseEvent& event );
		void OnMenuSelectionCamera( wxCommandEvent& event );
		void OnMenuSelectionExit( wxCommandEvent& event );
	public:
		/** Constructor */
		SigninMain( wxWindow* parent );
	//// end generated class members


public:
		bool Cancelled();
		bool m_cancelled;
		wxCriticalSection m_csCancelled;        // protects m_cancelled

		std::unique_ptr<wxProgressDialog> m_dlgProgress;

		void OnWorkerEvent(wxThreadEvent& event);
		void OnUpdateWorker(wxUpdateUIEvent& event);
		void OnStartWorker(wxCommandEvent& event);

	
};

#endif // __SigninMain__
