#ifndef __SigninMain__
#define __SigninMain__

/**
@file
Subclass of SigninFrame, which is generated by wxFormBuilder.
*/

#include "SigninFrame.h"
#include "./camera/CameraView.h"

//// end generated include

/** Implementing SigninFrame */
class SigninMain : public SigninFrame
{
	protected:
		CameraView * m_CameraView;

		// Handlers for SigninFrame events.
		void OnClose( wxCloseEvent& event );
		void OnMenuSelectionCamera( wxCommandEvent& event );
		void OnMenuSelectionExit( wxCommandEvent& event );
	public:
		/** Constructor */
		SigninMain( wxWindow* parent );
	//// end generated class members
	
};

#endif // __SigninMain__
